CREATE OR REPLACE TESTING_AUTOMATION_OUTPUT(
JOB_ID VARCHAR,
ISRT_DT_TM TIMESTAMP_NTZ(9),
INPUT_JOB_ID VARCHAR,
WORKSTREAM_NAME VARCHAR,
DATA_SRC_NAME VARCHAR,
ADO_TESTCASE_NO VARCHAR,
TEST_STEP VARCHAR,
TESTCASE_DESC VARCHAR,
SOURCE_QUERY VARCHAR,
TARGET_QUERY VARCHAR,
EXPECTED_RESULT VARCHAR,
TEST_SUITES VARCHAR,
TESTCASE_STATUS VARCHAR,
TESTED_BY VARCHAR,
COMMENT VARCHAR,
INSERTED_BY VARCHAR,
OUTPUT_ID VARCHAR
);